import { reqGetHeaders, reqApiHost } from "grandus-lib/utils";
import { get } from "lodash";
import cache, {
  outputCachedData,
  saveDataToCache,
} from "grandus-lib/utils/cache";

export default async (req, res) => {
  // if (await outputCachedData(req, res, cache)) return;

  const { query } = req;
  const result = await fetch(
    `${reqApiHost(req)}/api/v2/deliveries/possible-by-items?expand=${
      query?.expand
    }`,
    {
      method: "post",
      headers: reqGetHeaders(req),
      body: JSON.stringify({
        item: query?.items ? [...query?.items] : [],
      }),
    }
  ).then((r) => r.json());

  // saveDataToCache(req, cache, get(result, "data", {}));
  // res.status(get(result, "statusCode", 500)).json(get(result, "data", {}));
  res.status(200).json([
    {
      id: 712,
      groupName: "Košice - Tesco",
      name: "Košice - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 130,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 652,
      groupName: "Prievidza - Tesco",
      name: "Prievidza - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 168,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 661,
      groupName: "Žiar nad Hronom - Tesco",
      name: "Žiar nad Hronom - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 172,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 775,
      groupName: "Prešov - Tesco",
      name: "Prešov - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 180,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 356,
      groupName: "Test moznost (nemazat)",
      name: "Test moznost (nemazat)",
      price: 100,
      priceData: {
        price: 100,
        priceWithoutVat: 83.33,
        vatFraction: 16.67,
        vat: 20,
        priceFormatted: "100,00 €",
        priceWithoutVatFormatted: "83,33 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 355,
      duration: null,
      description: "",
      customCode: null,
      customType: 0,
      photo: null,
      group: "",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [],
    },
    {
      id: 1315,
      groupName: "Zásielkovňa",
      name: "Zásielkovňa",
      price: 1.5,
      priceData: {
        price: 1.5,
        priceWithoutVat: 1.25,
        vatFraction: 0.25,
        vat: 20,
        priceFormatted: "1,50 €",
        priceWithoutVatFormatted: "1,25 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 1312,
      duration: null,
      description: "",
      customCode: "",
      customType: 0,
      photo: null,
      group: "",
      serviceProviderType: 1,
      usable: 1,
      hash: "",
      operationUnitsRelations: [],
      payments: [
        {
          id: 190,
          name: "Zásielkovňa - platba na mieste",
          price: 2,
          priceData: {
            price: 2,
            priceWithoutVat: 1.67,
            vatFraction: 0.33,
            vat: 20,
            priceFormatted: "2,00 €",
            priceWithoutVatFormatted: "1,67 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 1,
          description: "",
          photo: null,
          options: null,
        },
        {
          id: 193,
          name: "Zásielkovňa - Online platba kartou",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description: "",
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 1300,
      groupName: "GLS - kuriér",
      name: "GLS - kuriér",
      price: 2,
      priceData: {
        price: 2,
        priceWithoutVat: 1.67,
        vatFraction: 0.33,
        vat: 20,
        priceFormatted: "2,00 €",
        priceWithoutVatFormatted: "1,67 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 1297,
      duration: null,
      description: "",
      customCode: "",
      customType: 0,
      photo: null,
      group: "",
      serviceProviderType: null,
      usable: 1,
      hash: "",
      operationUnitsRelations: [],
      payments: [
        {
          id: 1,
          name: "Dobierka",
          price: 2,
          priceData: {
            price: 2,
            priceWithoutVat: 1.67,
            vatFraction: 0.33,
            vat: 20,
            priceFormatted: "2,00 €",
            priceWithoutVatFormatted: "1,67 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 1,
          description: "",
          photo: null,
          options: null,
        },
        {
          id: 20,
          name: "Na splátky - Quatro",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 3,
          description: "",
          photo: null,
          options: null,
        },
        {
          id: 49,
          name: "Platba prevodom",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            "<p>Inform&aacute;cie k platbe V&aacute;m bud&uacute; doručen&eacute; <strong>e-mailom.</strong><br />\r\nPros&iacute;m, vykonajte<strong> &uacute;hradu e&scaron;te dnes, a to vždy za každ&uacute; objedn&aacute;vku samostatne</strong> s pr&iacute;slu&scaron;n&yacute;m variabiln&yacute;m symbolom.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 187,
          name: "Online platba kartou",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description: "",
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 1159,
      groupName: "Bratislava - Tesco Zl. Piesky",
      name: "Bratislava - Tesco Zl. Piesky",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 1156,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 649,
      groupName: "Bratislava - Vivo!",
      name: "Bratislava - Vivo!",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 164,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 1090,
      groupName: "Zlaté Moravce - TESCO",
      name: "Zlaté Moravce - TESCO",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 1087,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 1042,
      groupName: "Spišská Nová Ves - MADARAS",
      name: "Spišská Nová Ves - MADARAS",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 1036,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: "",
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 1057,
      groupName: "Bánovce nad Bebravou - Tesco",
      name: "Bánovce nad Bebravou - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 1051,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 1024,
      groupName: "Senec - Tesco",
      name: "Senec - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 1021,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 868,
      groupName: "Dunajská Streda",
      name: "Dunajská Streda",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 865,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 646,
      groupName: "Bratislava - Tesco Lamač",
      name: "Bratislava - Tesco Lamač",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 163,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 655,
      groupName: "Banská Bystrica - Tesco Extra",
      name: "Banská Bystrica - Tesco Extra",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 174,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 676,
      groupName: "Lučenec - OC Galéria",
      name: "Lučenec - OC Galéria",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 144,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 679,
      groupName: "Lučenec - Prior",
      name: "Lučenec - Prior",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 148,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 685,
      groupName: "Galanta - Tesco",
      name: "Galanta - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 121,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 772,
      groupName: "Malacky - Tesco",
      name: "Malacky - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 150,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 700,
      groupName: "Považská Bystrica - Tesco",
      name: "Považská Bystrica - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 146,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 703,
      groupName: "Nové Zámky - Tesco",
      name: "Nové Zámky - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 158,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 706,
      groupName: "Poprad - OC Max",
      name: "Poprad - OC Max",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 160,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 718,
      groupName: "Martin - Tesco",
      name: "Martin - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 152,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 721,
      groupName: "Sabinov - Kaufland",
      name: "Sabinov - Kaufland",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 119,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 724,
      groupName: "Dubnica nad Váhom - Tesco",
      name: "Dubnica nad Váhom - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 87,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 730,
      groupName: "Ružomberok - Tesco",
      name: "Ružomberok - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 128,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 739,
      groupName: "Banská Bystrica - Kaufland",
      name: "Banská Bystrica - Kaufland",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 110,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 727,
      groupName: "Rožňava - Tesco",
      name: "Rožňava - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 135,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 745,
      groupName: "Žilina - Tesco",
      name: "Žilina - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 93,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 742,
      groupName: "Trenčín - Tesco",
      name: "Trenčín - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 104,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 751,
      groupName: "Zvolen - Európa SC",
      name: "Zvolen - Európa SC",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 95,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 748,
      groupName: "Čadca - Tesco",
      name: "Čadca - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 111,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 766,
      groupName: "Šaľa - Kaufland",
      name: "Šaľa - Kaufland",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 114,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
    {
      id: 763,
      groupName: "Topolčany - Tesco",
      name: "Topolčany - Tesco",
      price: 1,
      priceData: {
        price: 1,
        priceWithoutVat: 0.83,
        vatFraction: 0.17,
        vat: 20,
        priceFormatted: "1,00 €",
        priceWithoutVatFormatted: "0,83 €",
        currency: "EUR",
        currencySymbol: "€",
      },
      priceToBeSpecified: 0,
      VAT: 20,
      lat: null,
      lng: null,
      parentId: 113,
      duration: null,
      description: "",
      customCode: "",
      customType: 1,
      photo: null,
      group: "Osobný odber",
      serviceProviderType: null,
      usable: 1,
      hash: null,
      operationUnitsRelations: [],
      payments: [
        {
          id: 3,
          name: "Platba kartou vopred",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 10,
          description:
            "<p>Online platba vopred prostredn&iacute;ctvom platobnej karty. Vyberte si zo zoznamu Va&scaron;ej preferovanej banky a uskutočnite platbu priamo pri vytvoren&iacute; objedn&aacute;vky.</p>\r\n",
          photo: null,
          options: null,
        },
        {
          id: 22,
          name: "V predajni",
          price: 0,
          priceData: {
            price: 0,
            priceWithoutVat: 0,
            vatFraction: 0,
            vat: 20,
            priceFormatted: "0,00 €",
            priceWithoutVatFormatted: "0,00 €",
            currency: "EUR",
            currencySymbol: "€",
          },
          VAT: 20,
          type: 0,
          description:
            '<p><span class="method_name">V hotovosti, alebo platobnou kartou.</span></p>\r\n',
          photo: null,
          options: null,
        },
      ],
    },
  ]);
};
